// <auto-generated />
namespace ExpenseManagingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class classUpdated02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(classUpdated02));
        
        string IMigrationMetadata.Id
        {
            get { return "202006051044143_classUpdated02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
